import { test } from "node:test"
import assert from "node:assert/strict"
import {
  scanDestructive,
  parseSquawk,
  hasNoSchemaChange,
  parseAllowedLosses,
  applyAllowances,
  migrationForLine,
} from "../.dagger/src/core/sql-scan.ts"

// The EF rename trap: this is exactly what EF emits when a property is renamed.
const RENAME_AS_DROP_ADD = `
ALTER TABLE orders DROP COLUMN "CreatedAt";
ALTER TABLE orders ADD "CreatedOn" timestamp with time zone NOT NULL DEFAULT now();
`

const PROPER_RENAME = `
ALTER TABLE orders RENAME COLUMN "CreatedAt" TO "CreatedOn";
`

test("catches the EF rename trap (DROP + ADD)", () => {
  const f = scanDestructive(RENAME_AS_DROP_ADD)
  assert.equal(f.length, 1)
  assert.equal(f[0].rule, "drop-column")
  assert.equal(f[0].line, 2)
})

test("a proper RENAME COLUMN passes", () => {
  assert.deepEqual(scanDestructive(PROPER_RENAME), [])
})

test("an allow-loss marker naming the column waives that statement (D6)", () => {
  const sql = `-- shipkit:allow-loss orders.CreatedAt  never populated in production\n${RENAME_AS_DROP_ADD}`
  assert.deepEqual(scanDestructive(sql), [])
})

test("a marker for one column does not excuse dropping another", () => {
  // The reason the marker names a target: a waiver obtained for one change must not let a
  // second, unintended destruction ride along inside the same migration.
  const sql = `-- shipkit:allow-loss orders.CreatedAt  reviewed
ALTER TABLE orders DROP COLUMN "CreatedAt";
ALTER TABLE orders DROP COLUMN "Reference";`
  const f = scanDestructive(sql)
  assert.equal(f.length, 1)
  assert.match(f[0].sql!, /Reference/)
})

test("parseAllowedLosses reads the targets and strips quotes", () => {
  const sql = `-- shipkit:allow-loss "orders"."CreatedAt"  reviewed
-- shipkit:allow-loss legacy_orders  table is unused`
  assert.deepEqual(parseAllowedLosses(sql), ["orders.CreatedAt", "legacy_orders"])
})

test("a marker inside a string literal does not suppress the gate", () => {
  const sql = `INSERT INTO notes (body) VALUES ('-- shipkit:allow-loss orders.CreatedAt nice try');\nALTER TABLE orders DROP COLUMN "CreatedAt";`
  const f = scanDestructive(sql)
  assert.equal(f.length, 1, "the literal must not be read as a marker")
  assert.equal(f[0].rule, "drop-column")
})

test("catches DROP TABLE and ALTER COLUMN ... TYPE", () => {
  const f = scanDestructive(`DROP TABLE legacy_orders;\nALTER TABLE orders ALTER COLUMN total TYPE numeric(18,2);`)
  assert.deepEqual(f.map((x) => x.rule), ["drop-table", "alter-column-type"])
})

test("an ordinary additive migration passes", () => {
  const f = scanDestructive(`
    ALTER TABLE orders ADD "Note" text NULL;
    CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_orders_created_at ON orders (created_at);
  `)
  assert.deepEqual(f, [])
})

test("unparseable Squawk output is a finding, never a pass", () => {
  const f = parseSquawk("panic: something went wrong")
  assert.equal(f.length, 1)
  assert.equal(f[0].rule, "squawk-output-unparseable")
})

test("empty Squawk output is a pass", () => {
  assert.deepEqual(parseSquawk("   "), [])
})

test("parses Squawk findings and converts its zero-based line", () => {
  // Verified against squawk-cli 2.65.0: `line` is zero-based, so a finding on the first
  // line of the file arrives as 0. Reporting it unchanged points the reader one line early.
  const f = parseSquawk(JSON.stringify([
    {
      rule_name: "require-concurrent-index-creation",
      file: "migration.sql",
      line: 13,
      message: "Concurrent index creation is preferred",
      help: "Use CREATE INDEX CONCURRENTLY",
    },
  ]))
  assert.equal(f[0].rule, "require-concurrent-index-creation")
  assert.equal(f[0].line, 14, "zero-based 13 is line 14")
  assert.match(f[0].message!, /Concurrent index creation is preferred — Use CREATE INDEX CONCURRENTLY/)
})

test("a finding on the very first line is reported as line 1, not line 0", () => {
  const f = parseSquawk(JSON.stringify([{ rule_name: "ban-drop-column", line: 0 }]))
  assert.equal(f[0].line, 1)
})

// --- Real output captured from fixtures/dotnet-api on 2026-09-12 -------------------------

/** `dotnet ef migrations script 0` with one migration compiled in. */
const REAL_INITIAL_SCRIPT = `﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Reference" character varying(64) NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260912083112_InitialCreate', '10.0.12');

COMMIT;
`

/**
 * What EF actually writes when nothing is pending — or when the assembly is stale and it
 * cannot see the new migration. Three bytes: a UTF-8 BOM. The two cases are indistinguishable
 * from the file alone, which is why the pending list is cross-checked against it.
 */
const REAL_EMPTY_SCRIPT = "﻿"

test("a real EF script is recognised as containing schema changes", () => {
  assert.equal(hasNoSchemaChange(REAL_INITIAL_SCRIPT), false)
})

test("EF's BOM-only output is recognised as empty", () => {
  assert.equal(hasNoSchemaChange(REAL_EMPTY_SCRIPT), true)
})

test("a script with only EF history bookkeeping is empty", () => {
  // The stale-assembly case: EF emits the history table but no migration of its own.
  const historyOnly = `﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);
`
  assert.equal(hasNoSchemaChange(historyOnly), true)
})

test("a commented-out DDL statement does not count as a schema change", () => {
  assert.equal(hasNoSchemaChange(`-- CREATE TABLE orders (id int);`), true)
})

test("the BOM does not hide a destructive statement on the first line", () => {
  const f = scanDestructive(`﻿ALTER TABLE orders DROP COLUMN "CreatedAt";`)
  assert.equal(f.length, 1)
  assert.equal(f[0].rule, "drop-column")
})

test("the real initial migration is not destructive", () => {
  assert.deepEqual(scanDestructive(REAL_INITIAL_SCRIPT), [])
})

test("an allow-loss marker waives the matching Squawk finding", () => {
  const sql = `-- shipkit:allow-loss orders.CreatedAt  reviewed
ALTER TABLE orders DROP COLUMN "CreatedAt";`
  const findings = [{ rule: "ban-drop-column", line: 2 }]
  assert.deepEqual(applyAllowances(findings, sql, ["orders.CreatedAt"]), [])
})

test("a marker does not waive a Squawk finding on a different line", () => {
  const sql = `-- shipkit:allow-loss orders.CreatedAt  reviewed
ALTER TABLE orders DROP COLUMN "CreatedAt";
ALTER TABLE orders DROP COLUMN "Reference";`
  const findings = [
    { rule: "ban-drop-column", line: 2 },
    { rule: "ban-drop-column", line: 3 },
  ]
  const left = applyAllowances(findings, sql, ["orders.CreatedAt"])
  assert.equal(left.length, 1)
  assert.equal(left[0].line, 3)
})

test("a marker never waives a non-destructive rule", () => {
  const sql = `-- shipkit:allow-loss orders.CreatedAt  reviewed
CREATE INDEX ix ON orders ("CreatedAt");`
  const findings = [{ rule: "require-concurrent-index-creation", line: 2 }]
  assert.equal(applyAllowances(findings, sql, ["orders.CreatedAt"]).length, 1)
})

// --- which migration a script line belongs to (#5) ---

// The shape `dotnet ef migrations script` emits, taken from a real project that uses
// EFCore.NamingConventions (snake_case history columns).
const COMBINED = `START TRANSACTION;
ALTER TABLE bookings ADD passenger_count integer;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260906123517_OptionalPassengerCount', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE routes RENAME COLUMN origin TO origin_place_key;
ALTER TABLE routes DROP COLUMN legacy_code;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260906204842_RenameRouteEndpoints', '10.0.1');

COMMIT;
`

test("a finding is attributed to the migration whose block contains it", () => {
  assert.equal(migrationForLine(COMBINED, 2, "__EFMigrationsHistory"), "20260906123517_OptionalPassengerCount")
  assert.equal(migrationForLine(COMBINED, 10, "__EFMigrationsHistory"), "20260906204842_RenameRouteEndpoints")
  assert.equal(migrationForLine(COMBINED, 11, "__EFMigrationsHistory"), "20260906204842_RenameRouteEndpoints")
})

test("the default EF column names work the same", () => {
  const sql = `ALTER TABLE "Orders" DROP COLUMN "Legacy";\nINSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")\nVALUES ('20260912083112_InitialCreate', '10.0.0');`
  assert.equal(migrationForLine(sql, 1, "__EFMigrationsHistory"), "20260912083112_InitialCreate")
})

test("a trailing COMMIT after the last record belongs to the last migration", () => {
  assert.equal(migrationForLine(COMBINED, 16, "__EFMigrationsHistory"), "20260906204842_RenameRouteEndpoints")
})

test("a leading BOM does not shift the attribution", () => {
  assert.equal(migrationForLine("\uFEFF" + COMBINED, 2, "__EFMigrationsHistory"), "20260906123517_OptionalPassengerCount")
})

test("a script that records no migration attributes nothing", () => {
  assert.equal(migrationForLine("DROP TABLE x;", 1, "__EFMigrationsHistory"), undefined)
})
