#!/usr/bin/env python3
"""
Replays every command shape the pipeline sends, over SSH, with the pipeline's own key.

Never run this against production: it uploads files, takes no deploy lock, and the point of it
is the twelve things at the end that must be refused. SHIPKIT_REPLAY_HOST and SHIPKIT_REPLAY_KEY
override the test server it defaults to.

The shapes come from shapes.jsonl (tools/emit-ssh-shapes.ts), which was generated by the
module's own functions, not by transcribing them. A shape passes when the dispatcher is not what stopped it: the remote command
may still fail on its own (there is no real migration bundle here), but the refusal banner must
not appear and the connection must not be closed by the forced command.
"""
import base64, json, re, socket, subprocess, sys, os, pathlib, tempfile, time

KEY = os.path.expanduser(os.environ.get("SHIPKIT_REPLAY_KEY", "~/.ssh/shipkit_deploy_test"))
HOST = os.environ.get("SHIPKIT_REPLAY_HOST", "deploy@173.242.58.240")
SSH = ["ssh", "-i", KEY, "-o", "IdentitiesOnly=yes", "-o", "BatchMode=yes",
       "-o", "StrictHostKeyChecking=accept-new", HOST]
REFUSAL = "shipkit: this key is restricted"
HERE = pathlib.Path(__file__).parent
# shapes.jsonl wherever emit-ssh-shapes.ts was told to write it: the working directory first,
# then next to this script.
SHAPES = next((p for p in (pathlib.Path("shapes.jsonl"), HERE / "shapes.jsonl") if p.exists()), None)
if SHAPES is None:
    sys.exit("no shapes.jsonl; run: node --experimental-strip-types tools/emit-ssh-shapes.ts > shapes.jsonl")

def run(argv, stdin=b"", timeout=180):
    p = subprocess.run(argv, input=stdin, capture_output=True, timeout=timeout)
    return p.returncode, p.stdout.decode(errors="replace"), p.stderr.decode(errors="replace")

def send(script):
    return run(SSH + ["sh"], script.encode())

results = []
def record(name, rc, out, err, must_be_allowed=True):
    refused = REFUSAL in err
    ok = (not refused) if must_be_allowed else refused
    results.append((ok, name, "refused" if refused else f"passed dispatcher (exit {rc})",
                    (out or err).strip().replace("\n", " | ")[:160]))

shapes = [json.loads(l) for l in open(SHAPES)]
by = {s["name"]: s for s in shapes}

print("=== shapes the pipeline sends: every one must get through ===")
for s in shapes:
    if s["kind"] != "script":
        continue
    rc, out, err = send(s["text"])
    record(s["name"], rc, out, err)

# migrate/run-bundle: stdin is the DSN assignment followed by the script.
local = by["migrate/run-bundle"]["text"]
script = base64.b64decode(re.search(r"echo ([A-Za-z0-9+/=]+) \| base64 -d", local).group(1)).decode()
stdin = "SHIPKIT_DSN_B64=" + base64.b64encode(b"Host=x;Password=p$a'ss").decode() + "\n" + script
rc, out, err = send(stdin)
record("migrate/run-bundle", rc, out, err)

# The two scp uploads, to their real destinations.
payload = pathlib.Path(tempfile.mkdtemp()) / "payload.bin"
payload.write_bytes(b"shipkit replay\n")
for name in ("backup/scp-dump", "migrate/scp-bundle"):
    line = [l for l in by[name]["text"].split("\n") if l.startswith("scp ")][0]
    target = line.rsplit(":", 1)[1]
    if name == "migrate/scp-bundle":
        rc0, made, _ = send("umask 077 && mktemp -d /tmp/shipkit-efbundle.XXXXXX")
        target = made.strip().split("\n")[-1] + "/efbundle"
    else:
        send("umask 077 && mkdir -p /var/backups/shipkit/shipkit-probe && test -w /var/backups/shipkit/shipkit-probe")
    # -O for the same reason the pipeline passes it (SCP_LEGACY in core/ssh-command.ts):
    # without it OpenSSH 9 opens the sftp subsystem and the destination never appears in a
    # command the forced command could check.
    rc, out, err = run(["scp", "-O", "-i", KEY, "-o", "IdentitiesOnly=yes", "-o", "BatchMode=yes",
                        "-o", "StrictHostKeyChecking=accept-new", str(payload), f"{HOST}:{target}"])
    record(name + " -> " + target, rc, out, err)

for ok, name, verdict, detail in results:
    print(f"{'PASS' if ok else 'FAIL'}  {name:<46} {verdict:<28} {detail}")

print("\n=== things this key must NOT be able to do ===")
neg = []

def judge(name, refused, rc, detail):
    neg.append((refused, name, f"exit {rc}", (detail or "").strip().replace("\n", " | ")[:150]))

def by_banner(name, argv, stdin=b"", timeout=60):
    """Refused only when the dispatcher says so.

    Never by "Permission denied": that is also what a broken key, a wrong path and an ordinary
    file mode produce, so accepting it turns any failure at all into a green refusal. It did
    exactly that once — `cat /etc/shadow` was scored as refused when it had actually run.
    """
    try:
        rc, out, err = run(argv, stdin, timeout=timeout)
    except subprocess.TimeoutExpired:
        judge(name, False, "timeout", "still running after %ds" % timeout)
        return
    judge(name, REFUSAL in err, rc, err or out)

def by_absence(name, argv, path, stdin=b"", timeout=60):
    """For scp and sftp, which report a forced command's refusal only as "Connection closed".

    The evidence is the file: it must not be there afterwards.
    """
    path = pathlib.Path(path)
    if path.exists():
        path.unlink()
    try:
        rc, out, err = run(argv, stdin, timeout=timeout)
    except subprocess.TimeoutExpired:
        judge(name, False, "timeout", "still running after %ds" % timeout)
        return
    got = path.exists()
    judge(name, not got, rc, ("FETCHED %d bytes" % path.stat().st_size) if got
          else "nothing was written; " + (err or out))

def forward_is_dead(name, local_port, target, timeout=25):
    """A local forward the server refuses still opens a listening socket on this side.

    So the socket proves nothing and has to be used: the refusal is visible only when traffic is
    pushed through it. The harness used to just hold `ssh -N -L` open and time out, which killed
    the whole run before it printed anything.
    """
    proc = subprocess.Popen(
        ["ssh", "-i", KEY, "-o", "IdentitiesOnly=yes", "-o", "BatchMode=yes",
         "-o", "StrictHostKeyChecking=accept-new", "-o", "ExitOnForwardFailure=yes",
         "-N", "-L", f"{local_port}:{target}", HOST],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    banner = b""
    try:
        deadline = time.time() + timeout
        while time.time() < deadline and proc.poll() is None:
            try:
                with socket.create_connection(("127.0.0.1", local_port), timeout=3) as sock:
                    sock.settimeout(4)
                    banner = sock.recv(64)
                break
            except OSError:
                time.sleep(0.5)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
        err = (proc.stderr.read() or b"").decode(errors="replace")
    judge(name, not banner, "n/a",
          ("the forward CARRIED TRAFFIC: " + banner.decode(errors="replace")) if banner
          else "nothing came back; " + err)

SCP = ["scp", "-O", "-i", KEY, "-o", "IdentitiesOnly=yes", "-o", "BatchMode=yes",
       "-o", "StrictHostKeyChecking=accept-new"]
stolen = payload.parent / "stolen.txt"

by_banner("an interactive shell", SSH)
by_banner("a shell via the sh channel", SSH + ["sh"], b"cat /etc/shadow")
by_banner("docker run mounting the host root", SSH + ["sh"],
          b"docker run --rm -v /:/host alpine cat /host/etc/shadow")
by_banner("docker run --privileged (kamal channel)", SSH + ["docker run --rm --privileged alpine id"])
by_banner("docker socket mount (kamal channel)", SSH +
          ["docker run --rm -v /var/run/docker.sock:/var/run/docker.sock alpine id"])
by_banner("host bind mount (kamal channel)", SSH + ["docker run --rm -v /etc:/e alpine cat /e/shadow"])
by_banner("appending to the pipeline's own authorized_keys", SSH + ["sh"],
          b"echo pwned >> /home/deploy/.ssh/authorized_keys")
by_banner("a psql meta-command inside allowed SQL", SSH + ["sh"],
          b"docker exec -i shipkit-probe-db psql -v ON_ERROR_STOP=1 -U postgres -d probe -tA "
          b"<<'SHIPKIT_SQL'\n\\! id\nSHIPKIT_SQL\n")
by_banner("scp a file to somewhere it does not belong",
          SCP + [str(payload), f"{HOST}:/home/deploy/.ssh/authorized_keys2"])
by_absence("scp a file OFF the server", SCP + [f"{HOST}:/etc/hostname", str(stolen)], stolen)
by_absence("sftp", ["sftp", "-b", "-", "-i", KEY, "-o", "IdentitiesOnly=yes",
                    "-o", "BatchMode=yes", "-o", "StrictHostKeyChecking=accept-new", HOST],
           stolen, b"get /etc/hostname " + str(stolen).encode() + b"\n")
forward_is_dead("a port forward into the server's network", 15432, "127.0.0.1:22")

for ok, name, verdict, detail in neg:
    print(f"{'PASS' if ok else 'FAIL'}  {name:<46} {verdict:<12} {detail}")

# --------------------------------------------------------------------------------------------
# What this key CAN still do, asserted so that it stays visible.
#
# Kamal's channel is a deny-list, so a command that is not docker-shaped runs as `deploy`. That
# is the documented design (docs/runbooks/deploy-key.md), not an oversight — but a gap nobody
# is asked to look at stops being a known gap. It is checked here in the direction it actually
# behaves, so this prints FAIL on the day someone closes it and forgets to say so.
# --------------------------------------------------------------------------------------------
print("\n=== the known gap: Kamal's channel is default-allow ===")
rc, out, err = run(SSH + ["id"])
gap_open = REFUSAL not in err and "uid=" in out
print(f"{'as documented' if gap_open else 'CHANGED'}  an arbitrary non-docker command runs as deploy"
      f"  -> {(out or err).strip()[:80]}")

bad = [n for ok, n, _, _ in results + neg if not ok]
print("\n" + ("ALL PASS" if not bad else f"{len(bad)} FAILED: " + "; ".join(bad)))
sys.exit(1 if bad else 0)
